# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-19 22:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_isbn', models.CharField(max_length=50, unique=True)),
                ('book_name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('author', models.CharField(max_length=100, null=True)),
                ('publisher', models.CharField(max_length=100)),
                ('publish_time', models.CharField(max_length=50)),
                ('teacher', models.CharField(max_length=200)),
                ('book_info', models.CharField(max_length=255, null=True)),
                ('is_order', models.CharField(max_length=10)),
                ('remarks', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'books',
            },
        ),
        migrations.CreateModel(
            name='Bookscart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.CharField(max_length=30)),
                ('isbn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.books', to_field='book_isbn')),
            ],
            options={
                'db_table': 'bookscart',
            },
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('student_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(default=123456, max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=5)),
                ('class_1', models.CharField(max_length=20)),
                ('tel', models.CharField(max_length=11, null=True)),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
